### ISSUE TITLE
can't compile (BLE related)

### ISSUE THREAD

**Issue by mars3142** [StuckAtPrototype/PCB_business_card_remake#1]
I installed `ESP-IDF 5.4.0` and tried to build your code. But I got some error:

```
firmware/main/gap.h:4:10: fatal error: host/ble_hs.h: No such file or directory
```

Within the main.c I got three include errors:

```
#include "gap.h"
#include "gatt_svr.h"
#include "esp_bt.h"
```

This files can't be fully resolved (because of transient dependencies).

**Comment by StuckAtPrototype** [comment]
Hi! as mentioned in the readme, make sure you enable NIMBLE via menuconfig. Let me know if this solves it!

**Comment by mars3142** [comment]
This takes me one step further. I created a ```sdkconfig.defaults``` file (I'll create a PR later). So I don't need to do ```idf.py menuconfig``` manually. But now I got another issue while linking

```
undefined reference to `usb_serial_jtag_vfs_use_driver'
````

**Comment by mars3142** [comment]
Weird. After a complete fresh checkout with just the nimble fix, it worked. Will create a PR now.
